.TH mp3finder 1 "2024-05-08" "1.0" "mp3finder Manual"

.SH NAME
.B mp3finder
 \- A tool for finding and sorting MP3 files by tags in the current directory
.SH SYNOPSIS
.B ./mp3finder.sh
[\fIoptions\fR]
.SH DESCRIPTION
.B mp3finder
is a tool that enables users to view all MP3 files in the current directory in a sorted and color-coded format. Users can query desired files, and the tool will provide a list of all MP3 files sorted and color-coded based on their tags.

.B mp3finder
supports the following features:
.IP \[bu] 2
Tag-based sorting
.IP \[bu] 2
Color-coded display for easy identification
.IP \[bu] 2
Simple and intuitive command-line interface

.PP
The tool is especially useful for organizing large collections of MP3 files and quickly finding specific tracks based on metadata.

.SH OPTIONS
.TP
\fB-h\fR, \fB--help\fR
Displays help information and usage instructions.

.SH EXAMPLES
.PP
To run mp3finder and display all MP3 files in the current directory, use:
.EX
$ ./mp3finder.sh
.EE

.PP
To display help information:
.EX
$ ./mp3finder.sh -h
.EE

.SH BUGS
There are no known bugs at this time. If you encounter any issues, please report them to the author.

.SH AUTHOR
Written by Tamara Mruk.